[book]
authors = ["Jeroen Wijenbergh"]
language = "en"
multilingual = false
src = "src"
title = "eduVPN-common documentation"

[output.html]
site-url = "/eduvpn-common/"
additional-css = ["custom.css"]
